name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  setup-build-login-publish:
    name: Setup, Build, Login, Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
          
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.3.0
      with:
        url: http://52.186.95.76:8200
        method: github
        githubToken: ${{ secrets.USER_PAT }}
        secrets: |
          secret/data/github/sample-flask-app COLOR;

    # Build the Docker image
    - name: Build
      run: |-
        echo "Application will be colored ${COLOR}."
        docker build --build=arg COLOR=$COLOR \
          --tag "sainihimanshu983/sample-docker-app:${GITHUB_SHA}-$COLOR" .


    # Login to docker hub
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


    # Push the Docker image to Container Registry
    - name: Publish
      run: |-
        docker push "sainihimanshu983/sample-docker-app:${GITHUB_SHA}-$COLOR"

